config/routes.rb
CheckMate::Application.routes.draw do
  resources :habit_links

  post "lift/login"
  get "lift/habits"

  post "withings/notify"

  devise_for :users

  get 'oauth_consumers/withings/callback'  => 'withings_oauth_consumer#callback',  defaults: {id: 'withings'}
  get 'oauth_consumers/withings/callback2' => 'withings_oauth_consumer#callback2', defaults: {id: 'withings'}

  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  get "pages/index"
  root to: 'pages#index'

end

app/views/pages/index.html.haml
.step 
  - if !user_signed_in?
    %h3 Step 1. Log in with your <a href="http://lift.do" target="blank">Lift.do</a> account
    =form_tag('/lift/login', method: 'post', class: 'form-inline') do
      %input{type: 'text', placeholder: 'Email', name: 'email'}
      %input{type: 'password', placeholder: 'Password', name: 'password'}
      %button.btn.btn-primary Log in
  - else
    %h3 Step 1. Log in with your <a href="http://lift.do" target="blank">Lift.do</a> account
    %h3{style: 'font-size:30px'}
      =image_tag current_user.picture_url
      =current_user.full_name

.step
  - if user_signed_in?
    %h3 Step 2. Connect your accounts
    -@services.each do |service|
      .service{style: 'display: inline'}
        %img{src: "#{service[:image]}", style: 'width:50px'}
        -if service[:connected]
          %strong #{service[:name]}:
          Connected
        -else
          = link_to "Connect #{service[:name]} account", service[:path]
  - else
    %h3.inactive Step 2. Connect your accounts

.step
  - if user_signed_in?
    %h3 Step 3. Link your checkins
    When I
    %p
    -@triggers.each do |trigger|
      %label.radio
        -if trigger[:enabled]
          %input{name: 'trigger', type: 'radio', value: "#{trigger[:id]}"}
        -else
          %input{name: 'trigger', type: 'radio', value: "#{trigger[:id]}", disabled: 'disabled'}
        #{trigger[:label]}
    then check me in to:
    %p
    %div{style: 'font-style:italic', 'data-bind' => 'if: !habits'} <img src="/assets/loading.gif" /> Loading habits...
    %div{'data-bind' => 'visible: habits', style: 'display:none'}
      =form_tag(habit_links_path, class: 'form-inline') do
        %select#habits{'data-bind' => 'options: habits, optionsText: "name", optionsValue: "id"', name: 'habit_id'}
        %p
        %button.btn.btn-primary
          %i.icon-plus.icon-white
          Link Checkins